### ISSUE TITLE
The data 

### ISSUE THREAD

**Issue by mgilgamesh** [quantumiracle/Cascading-Decision-Tree#2]
Would you please provide the following data?

**Comment by quantumiracle** [comment]
which one?

**Comment by mgilgamesh** [comment]
The File Structure   has data , src and visual  folder ，but the data folder can not be found

**Comment by quantumiracle** [comment]
sorry, I'm not gonna upload data here. This repo will maintain the code scripts only. It should be quite straightforward to generate all the necessary data for the experiments following the steps.

**Comment by mgilgamesh** [comment]
It means that I should produce the data by my myself

**Comment by quantumiracle** [comment]
Yes, you should. You will need some pretrained RL agents for collecting some of the data.
