### ISSUE TITLE
an error occurred when running code

### ISSUE THREAD

**Issue by gaozhongy** [quantumiracle/Cascading-Decision-Tree#4]
I have run the first part of the code：**python rl_data_collect.py**. But the following errors appeared below：
**PermissionError: [Errno 13] Permission denied: '../data/mlp/model/cartpole/ppo'**
Is it because my data is incomplete?

**Comment by 191870014** [comment]
> I have run the first part of the code：**python rl_data_collect.py**. But the following errors appeared below： **PermissionError: [Errno 13] Permission denied: '../data/mlp/model/cartpole/ppo'** Is it because my data is incomplete?

did you solve it? why i don't have the '../data' file?

**Comment by gaozhongy** [comment]
> > I have run the first part of the code：**python rl_data_collect.py**. But the following errors appeared below： **PermissionError: [Errno 13] Permission denied: '../data/mlp/model/cartpole/ppo'** Is it because my data is incomplete?
> 
> did you solve it? why i don't have the '../data' file?
No, I also don't have this file, so the above error is caused

**Comment by quantumiracle** [comment]
Hi, 

Sorry for the late reply and thanks for you interests in the repo.
When creating the repo I didn't track the data folder on git, so there is no `/data` folder. You can directly create the folder `./data` to run the code. Hope this will solve the issue. 

If there is still any problem, feel free to shoot an email to zhding96@gmail.com, since I might not check the reply under the repo in time.

**Comment by quantumiracle** [comment]
Actually, I just managed to find the data files, but it's not guaranteed that these files are exactly the ones to replicate the results in the paper (It's a long time and I didn't check if the data match with the paper). At least it's a good reference for you guys to take a look at the folder structure and save your time, you may regenerate those data. 

I put the data folders [here in Google Drive](https://drive.google.com/drive/folders/18GGBNZhugIAQXJ1TXtwJBwI6HkDWIJay?usp=sharing) , simply download and leave them at the root of the repo.

I also updated the readme.

**Comment by gaozhongy** [comment]
> Actually, I just managed to find the data files, but it's not guaranteed that these files are exactly the ones to replicate the results in the paper (It's a long time and I didn't check if the data match with the paper). At least it's a good reference for you guys to take a look at the folder structure and save your time, you may regenerate those data.
> 
> I put the data folders [here in Google Drive](https://drive.google.com/drive/folders/18GGBNZhugIAQXJ1TXtwJBwI6HkDWIJay?usp=sharing) , simply download and leave them at the root of the repo.
> 
> I also updated the readme.

Thank you for helping to answer this question o (￣ ▽ ￣) d
